#!node.exe

// Sorry for an extra dependency 😥 I really love the easy to go lazy approach with nodejs, and didn't go for like an extensive bash script to do the job

const process = require("node:process");
const fs = require("node:fs");

if (process.argv.length < 4) {
    console.log(`Usage: ${process.argv[1]} <isrs_gen.c> <isrs_gen.inc>`);
    process.exit(1);
}

const timestamp = new Date();
const ISRS_WITH_ERROR = [8, 10, 11, 12, 13, 14, 17, 21, 29, 30];

let isrOut_C =
`//
// >>> DO NOT EDIT, THIS FILE IS AUTOGENERATED <<<
// Generated by genISR.js from <projectRoot>/scripts
// Created on ${timestamp.toDateString()} ${timestamp.toTimeString()}
// To be used alongside isr.c in <projectRoot>/kernel/wat_c/system
//

#include "../include/gdt_inc.h"
#include "idt.h"

`;

for (let i = 0; i <= 255; i++) {
    isrOut_C += `void _cdecl x86_ISR${i}();\n`;
}

isrOut_C += "\nvoid ISR_Initialise()\n{\n";

for (let i = 0; i <= 255; i++) {
    isrOut_C += `        IDT_SetGate(${i}, x86_ISR${i}, GDT_32_BIT_CODE_SEGMENT, IDT_FLAG_DPL_RING0 | IDT_FLAG_32_INTERRUPT_GATE);\n`;
}

isrOut_C += "}\n";

fs.writeFileSync(process.argv[2], isrOut_C);

let isrOut_INC =
`;
; >>> DO NOT EDIT, THIS FILE IS AUTOGENERATED <<<
; Generated by genISR.js from <projectRoot>/scripts
; Created on ${timestamp.toDateString()} ${timestamp.toTimeString()}
; To be used alongside isr.s in <projectRoot>/kernel/asm
;

`;

for (let i = 0; i <= 255; i++) {
    if (ISRS_WITH_ERROR.includes(i)) {
        isrOut_INC += `ISR_ERROR ${i}\n`;
    }
    else {
        isrOut_INC += `ISR_NOERROR ${i}\n`;
    }
}

fs.writeFileSync(process.argv[3], isrOut_INC);